int_Hp_xT0_xR0 <- function(wR, p_0, p_1, p_2, a, b) {
  1/4*gamma(b)*(4*gamma(a)*gamma(a + b + 
                                   1)*gamma(a + b + 2)*p_0*wR^2-4*gamma(a + b)*gamma(a + 1)*gamma(a + b + 
                                                                                                    2)*p_0*wR^2-2*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                             1)*gamma(a + 2)*p_0*wR^2 + p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + p_2*wR^2*gamma(a + 
                                                                                                                                                                                                                                                                                               2)*gamma(a + b)*gamma(a + b + 1)-8*gamma(a)*gamma(a + b + 1)*gamma(a + b + 2)*p_0*wR + 8*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                b)*gamma(a + 1)*gamma(a + b + 2)*p_0*wR + 2*p_1*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     2)-2*gamma(a + b)*gamma(a + b + 1)*gamma(a + 2)*p_0*wR-p_1*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   + 1) + 4*gamma(a)*gamma(a + b + 1)*gamma(a + b + 2)*p_0-4*gamma(a + b)*gamma(a + 1)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               2)*p_0 + gamma(a + b)*gamma(a + b + 1)*gamma(a + 2)*p_0)/beta(a,b)/gamma(a + b)/gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1)/gamma(a + b + 2)
}

int_Ha_xT0_xR0 <- function(wR, p_0, p_1, p_2, a, b) {
  1/4*gamma(b)*(-2*p_0*p_1*wR^2*gamma(a + 
                                        2)*gamma(a + b)*gamma(a + b + 1) + 2*p_0*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 
                                                                                                                            1)-2*p_1*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-4*gamma(a + b + 2)*gamma(a)*gamma(a + b 
                                                                                                                                                                                                                           + 1)*p_0*p_1*wR^2 + 4*gamma(a + b + 2)*gamma(a)*gamma(a + b + 1)*p_0*p_2*wR^2 + 
                  6*p_0*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-4*gamma(a + b + 2)*gamma(a + b)*gamma(a + 
                                                                                                                    1)*p_0*p_2*wR^2 + 2*p_1*p_2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 3*p_0*p_1*wR*gamma(a + 
                                                                                                                                                                                                                       2)*gamma(a + b)*gamma(a + b + 1)-2*p_0*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                  p_1*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 4*gamma(a + b + 2)*gamma(a)*gamma(a + b + 
                                                                                                              1)*p_0*p_1*wR-8*p_0*p_1*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                           b)*gamma(a + b + 1)*p_0^2*wR^2 + p_1^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                  p_2^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 4*gamma(a + b + 2)*gamma(a)*gamma(a + b + 
                                                                                                              1)*p_0^2*wR^2-4*gamma(a + b + 2)*gamma(a + b)*gamma(a + 1)*p_0^2*wR^2-2*p_1^2*wR^2*gamma(a + 
                                                                                                                                                                                                         1)*gamma(a + b)*gamma(a + b + 2)-2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                                                                              1)*p_0^2*wR-p_1^2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-8*gamma(a + b + 2)*gamma(a)*gamma(a 
                                                                                                                                                                                                                                                                                                                                                                                + b + 1)*p_0^2*wR + 8*gamma(a + b + 2)*gamma(a + b)*gamma(a + 1)*p_0^2*wR + 2*p_1^2*wR*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1)*gamma(a + b)*gamma(a + b + 2)-p_0*p_1*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                  p_0*p_2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_0*p_1*gamma(a + 1)*gamma(a + b)*gamma(a + b 
                                                                                                                 + 2) + gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)*p_0^2 + 4*gamma(a + b + 2)*gamma(a)*gamma(a + b + 
                                                                                                                                                                                                               1)*p_0^2-4*gamma(a + b + 2)*gamma(a + b)*gamma(a + 1)*p_0^2)/beta(a,b)/gamma(a + b)/gamma(a + b + 
                                                                                                                                                                                                                                                                                                           1)/gamma(a + b + 2)
}

int_Hp_xT0_xR1 <- function(wR, p_0, p_1, p_2, a, b) {
  -1/4*gamma(b)*(8*gamma(a)*gamma(a + b + 
                                    1)*gamma(a + b + 2)*p_0*wR^2 + 2*gamma(a + b)*gamma(a + b + 1)*gamma(a + 2)*p_0*wR^2 + 
                   2*p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a 
                                                                                                                      + b + 1)-8*gamma(a + b)*gamma(a + 1)*gamma(a + b + 2)*p_0*wR^2-4*p_1*wR^2*gamma(a + 1)*gamma(a + 
                                                                                                                                                                                                                     b)*gamma(a + b + 2)-8*gamma(a)*gamma(a + b + 1)*gamma(a + b + 2)*p_0*wR-2*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                    1)*gamma(a + 2)*p_0*wR-2*p_1*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-2*p_2*wR*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                2)*gamma(a + b)*gamma(a + b + 1) + 8*gamma(a + b)*gamma(a + 1)*gamma(a + b + 2)*p_0*wR + 
                   4*p_1*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + p_1*gamma(a + 2)*gamma(a + b)*gamma(a + b + 
                                                                                                               1)-2*p_1*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2))/beta(a,b)/gamma(a + b)/gamma(a + b + 1)/gamma(a 
                                                                                                                                                                                                                  + b + 2)
}

int_Ha_xT0_xR1 <- function(wR, p_0, p_1, p_2, a, b) {
  -1/4*gamma(b)*(p_1^2*gamma(a + 2)*gamma(a + 
                                            b)*gamma(a + b + 1)-2*p_1^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-4*p_0*p_1*wR^2*gamma(a + 
                                                                                                                                          2)*gamma(a + b)*gamma(a + b + 1) + 4*p_0*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                              1)-4*p_1*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-8*gamma(a + b + 2)*gamma(a)*gamma(a + b 
                                                                                                                                                                                                                                                                                                                             + 1)*p_0*p_1*wR^2 + 8*gamma(a + b + 2)*gamma(a)*gamma(a + b + 1)*p_0*p_2*wR^2 + 
                   12*p_0*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-8*gamma(a + b + 2)*gamma(a + b)*gamma(a + 
                                                                                                                      1)*p_0*p_2*wR^2 + 4*p_1*p_2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 4*p_0*p_1*wR*gamma(a + 
                                                                                                                                                                                                                         2)*gamma(a + b)*gamma(a + b + 1)-4*p_0*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                   4*p_1*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 8*gamma(a + b + 2)*gamma(a)*gamma(a + b + 
                                                                                                                 1)*p_0*p_1*wR-12*p_0*p_1*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 2*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                                 b)*gamma(a + b + 1)*p_0^2*wR^2 + 2*p_1^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                   2*p_2^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 8*gamma(a + b + 2)*gamma(a)*gamma(a + b + 
                                                                                                                 1)*p_0^2*wR^2-8*gamma(a + b + 2)*gamma(a + b)*gamma(a + 1)*p_0^2*wR^2-4*p_1^2*wR^2*gamma(a + 
                                                                                                                                                                                                            1)*gamma(a + b)*gamma(a + b + 2)-2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                                                                                 1)*p_0^2*wR-2*p_1^2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-8*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                             2)*gamma(a)*gamma(a + b + 1)*p_0^2*wR + 8*gamma(a + b + 2)*gamma(a + b)*gamma(a + 1)*p_0^2*wR + 
                   4*p_1^2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-p_0*p_1*gamma(a + 2)*gamma(a + b)*gamma(a + b 
                                                                                                                 + 1) + 4*p_0*p_1*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-2*p_2^2*wR*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                             b)*gamma(a + b + 1)-p_1*p_2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-4*gamma(a + b + 2)*gamma(a + 
                                                                                                                                                                                                                                                                                                               b + 1)*gamma(a)*p_0*p_1 + 8*gamma(a + b + 2)*gamma(a + 1)*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                 b)*p_0*p_2*wR-4*p_1*p_2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-8*gamma(a + b + 2)*gamma(a + b 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                + 1)*gamma(a)*p_0*p_2*wR)/beta(a,b)/gamma(a + b)/gamma(a + b + 1)/gamma(a + b + 2)
}

int_Hp_xT0_xR2 <- function(wR, p_0, p_1, p_2, a, b) {
  -1/4*gamma(b)*(4*gamma(a + b)*gamma(a + 
                                        1)*gamma(a + b + 2)*p_0*wR^2 + 2*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-gamma(a + 
                                                                                                                                     b)*gamma(a + b + 1)*gamma(a + 2)*p_0*wR^2-p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                          1)-p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-4*gamma(a)*gamma(a + b + 1)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                     2)*p_0*wR^2-2*p_1*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + p_1*wR*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                   b)*gamma(a + b + 1) + 2*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-p_2*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      b)*gamma(a + b + 1))/beta(a,b)/gamma(a + b)/gamma(a + b + 1)/gamma(a + b + 2)
}

int_Ha_xT0_xR2 <- function(wR, p_0, p_1, p_2, a, b) {
  1/4*gamma(b)*(-2*p_0*p_1*wR^2*gamma(a + 
                                        2)*gamma(a + b)*gamma(a + b + 1) + 2*p_0*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 
                                                                                                                            1)-2*p_1*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-4*gamma(a + b + 2)*gamma(a)*gamma(a + b 
                                                                                                                                                                                                                           + 1)*p_0*p_1*wR^2 + 4*gamma(a + b + 2)*gamma(a)*gamma(a + b + 1)*p_0*p_2*wR^2 + 
                  6*p_0*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-4*gamma(a + b + 2)*gamma(a + b)*gamma(a + 
                                                                                                                    1)*p_0*p_2*wR^2 + 2*p_1*p_2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + p_0*p_1*wR*gamma(a + 
                                                                                                                                                                                                                     2)*gamma(a + b)*gamma(a + b + 1)-2*p_0*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                  3*p_1*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 4*gamma(a + b + 2)*gamma(a)*gamma(a + b + 
                                                                                                                1)*p_0*p_1*wR-4*p_0*p_1*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 4*gamma(a)*gamma(a + b + 
                                                                                                                                                                                                           2)*gamma(a + b + 1)*p_0*p_2-4*gamma(a + b)*gamma(a + b + 2)*gamma(a + 1)*p_0*p_2 + 2*p_1*p_2*gamma(a 
                                                                                                                                                                                                                                                                                                              + 1)*gamma(a + b)*gamma(a + b + 2) + gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)*p_0^2*wR^2 + 
                  p_1^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + p_2^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a 
                                                                                                                     + b + 1) + 4*gamma(a + b + 2)*gamma(a)*gamma(a + b + 1)*p_0^2*wR^2-4*gamma(a + b + 2)*gamma(a + 
                                                                                                                                                                                                                   b)*gamma(a + 1)*p_0^2*wR^2-2*p_1^2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-p_1^2*wR*gamma(a 
                                                                                                                                                                                                                                                                                                                     + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_1^2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 
                  p_0*p_2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-2*p_2^2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b 
                                                                                                                + 1)-p_1*p_2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + p_2^2*gamma(a + 2)*gamma(a + b)*gamma(a + 
                                                                                                                                                                                                                  b + 1) + 8*gamma(a + b + 2)*gamma(a + 1)*gamma(a + b)*p_0*p_2*wR-4*p_1*p_2*wR*gamma(a + 1)*gamma(a + 
                                                                                                                                                                                                                                                                                                                     b)*gamma(a + b + 2)-8*gamma(a + b + 2)*gamma(a + b + 1)*gamma(a)*p_0*p_2*wR)/beta(a,b)/gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                    b)/gamma(a + b + 1)/gamma(a + b + 2)
}

int_Hp_xT1_xR0 <- function(wR, p_0, p_1, p_2, a, b) {
  -1/2*gamma(b)*(2*gamma(a)*gamma(a + b + 
                                    2)*gamma(a + b + 1)*p_1*wR^2 + gamma(a + b)*gamma(a + b + 1)*gamma(a + 2)*p_0*wR^2 + 
                   p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b 
                                                                                                                  + 1)-2*gamma(a + b)*gamma(a + 1)*gamma(a + b + 2)*p_0*wR^2-2*p_1*wR^2*gamma(a + 1)*gamma(a + 
                                                                                                                                                                                                             b)*gamma(a + b + 2)-2*p_2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-2*gamma(a)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                          2)*gamma(a + b + 1)*p_1*wR-2*gamma(a + b)*gamma(a + b + 1)*gamma(a + 2)*p_0*wR-p_1*wR*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                        2)*gamma(a + b)*gamma(a + b + 1) + 4*gamma(a + b)*gamma(a + 1)*gamma(a + b + 2)*p_0*wR + 
                   2*p_1*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + gamma(a + b)*gamma(a + b + 1)*gamma(a + 
                                                                                                               2)*p_0-2*gamma(a + b)*gamma(a + 1)*gamma(a + b + 2)*p_0)/beta(a,b)/gamma(a + b)/gamma(a + b + 
                                                                                                                                                                                                       1)/gamma(a + b + 2)
}

int_Ha_xT1_xR0 <- function(wR, p_0, p_1, p_2, a, b) {
  -1/2*gamma(b)*(-2*gamma(a + b + 2)*gamma(a + 
                                             b + 1)*gamma(a)*p_1*p_2*wR^2-2*p_0*p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                   2*p_0*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-2*p_1*p_2*wR^2*gamma(a + 2)*gamma(a + 
                                                                                                                 b)*gamma(a + b + 1)-2*gamma(a + b + 2)*gamma(a)*gamma(a + b + 1)*p_0*p_1*wR^2 + 
                   4*p_0*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-4*gamma(a + b + 2)*gamma(a + b)*gamma(a + 
                                                                                                                     1)*p_0*p_2*wR^2 + 4*p_1*p_2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 3*p_0*p_1*wR*gamma(a + 
                                                                                                                                                                                                                        2)*gamma(a + b)*gamma(a + b + 1)-2*p_0*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                   p_1*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 4*gamma(a + b + 2)*gamma(a)*gamma(a + b + 
                                                                                                               1)*p_0*p_1*wR-6*p_0*p_1*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-2*p_2^2*wR^2*gamma(a + 
                                                                                                                                                                                                          1)*gamma(a + b)*gamma(a + b + 2) + 2*gamma(a + b + 2)*gamma(a + b + 1)*gamma(a)*p_1^2*wR^2-2*gamma(a 
                                                                                                                                                                                                                                                                                                             + b + 2)*gamma(a + b + 1)*gamma(a)*p_1^2*wR-2*gamma(a + b)*gamma(a + b + 2)*gamma(a + 1)*p_0*p_2 + 
                   gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)*p_0^2*wR^2 + p_1^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a 
                                                                                                                      + b + 1) + p_2^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-2*gamma(a + b + 2)*gamma(a + 
                                                                                                                                                                                                                  b)*gamma(a + 1)*p_0^2*wR^2-2*p_1^2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-2*gamma(a + 
                                                                                                                                                                                                                                                                                                               2)*gamma(a + b)*gamma(a + b + 1)*p_0^2*wR-p_1^2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                   4*gamma(a + b + 2)*gamma(a + b)*gamma(a + 1)*p_0^2*wR + 2*p_1^2*wR*gamma(a + 1)*gamma(a + b)*gamma(a 
                                                                                                                      + b + 2)-p_0*p_1*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + p_0*p_2*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                                 b)*gamma(a + b + 1) + 2*p_0*p_1*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-2*gamma(a + b + 
                                                                                                                                                                                                                                                                                                      2)*gamma(a + b + 1)*gamma(a)*p_0*p_1 + gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)*p_0^2-2*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                        b + 2)*gamma(a + b)*gamma(a + 1)*p_0^2 + 4*gamma(a + b + 2)*gamma(a + 1)*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         b)*p_0*p_2*wR-2*p_1*p_2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2))/beta(a,b)/gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  b)/gamma(a + b + 1)/gamma(a + b + 2)
}

int_Hp_xT1_xR1 <- function(wR, p_0, p_1, p_2, a, b) {
  1/2*gamma(b)*(2*gamma(a + b)*gamma(a + b + 
                                       1)*gamma(a + 2)*p_0*wR^2 + 2*p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                  2*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-4*gamma(a + b)*gamma(a + 1)*gamma(a + b + 
                                                                                                            2)*p_0*wR^2-4*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-4*p_2*wR^2*gamma(a + 1)*gamma(a + 
                                                                                                                                                                                                              b)*gamma(a + b + 2) + 4*gamma(a)*gamma(a + b + 2)*gamma(a + b + 1)*p_1*wR^2-2*gamma(a + b)*gamma(a + 
                                                                                                                                                                                                                                                                                                                 b + 1)*gamma(a + 2)*p_0*wR-2*p_1*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-2*p_2*wR*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                 2)*gamma(a + b)*gamma(a + b + 1) + 4*gamma(a + b)*gamma(a + 1)*gamma(a + b + 2)*p_0*wR + 
                  4*p_1*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 4*p_2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b 
                                                                                                                 + 2)-4*gamma(a)*gamma(a + b + 2)*gamma(a + b + 1)*p_1*wR + p_1*gamma(a + 2)*gamma(a + b)*gamma(a + b 
                                                                                                                                                                                                                + 1)-2*p_1*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 2*gamma(a + b + 2)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                   1)*gamma(a)*p_1)/beta(a,b)/gamma(a + b)/gamma(a + b + 1)/gamma(a + b + 2)
}

int_Ha_xT1_xR1 <- function(wR, p_0, p_1, p_2, a, b) {
  -1/2*gamma(b)*(-4*p_2^2*wR*gamma(a + 
                                     1)*gamma(a + b)*gamma(a + b + 2)-p_1^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_1^2*gamma(a 
                                                                                                                                       + 1)*gamma(a + b)*gamma(a + b + 2)-2*gamma(a)*gamma(a + b + 1)*gamma(a + b + 2)*p_1^2 + 4*gamma(a + 
                                                                                                                                                                                                                                         b + 2)*gamma(a + b + 1)*gamma(a)*p_1*p_2*wR^2 + 4*p_0*p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b 
                                                                                                                                                                                                                                                                                                                                        + 1)-4*p_0*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 4*p_1*p_2*wR^2*gamma(a + 2)*gamma(a 
                                                                                                                                                                                                                                                                                                                                                                                                                                           + b)*gamma(a + b + 1) + 4*gamma(a + b + 2)*gamma(a)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1)*p_0*p_1*wR^2-8*p_0*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 8*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             2)*gamma(a + b)*gamma(a + 1)*p_0*p_2*wR^2-8*p_1*p_2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2)-4*p_0*p_1*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 4*p_0*p_2*wR*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       b)*gamma(a + b + 1)-4*p_1*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-4*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             2)*gamma(a)*gamma(a + b + 1)*p_0*p_1*wR + 8*p_0*p_1*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2)-4*gamma(a)*gamma(a + b + 1)*gamma(a + b + 2)*p_1*p_2*wR + 4*p_2^2*wR^2*gamma(a + 1)*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     b)*gamma(a + b + 2)-4*gamma(a + b + 2)*gamma(a + b + 1)*gamma(a)*p_1^2*wR^2 + 4*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             2)*gamma(a + b + 1)*gamma(a)*p_1^2*wR-2*p_1*p_2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-2*gamma(a 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                + 2)*gamma(a + b)*gamma(a + b + 1)*p_0^2*wR^2-2*p_1^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1)-2*p_2^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 4*gamma(a + b + 2)*gamma(a + b)*gamma(a 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                + 1)*p_0^2*wR^2 + 4*p_1^2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 2*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   b)*gamma(a + b + 1)*p_0^2*wR + 2*p_1^2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-4*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  2)*gamma(a + b)*gamma(a + 1)*p_0^2*wR-4*p_1^2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 
                   p_0*p_1*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-2*p_0*p_1*gamma(a + 1)*gamma(a + b)*gamma(a + b + 
                                                                                                                  2) + 2*p_2^2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + p_1*p_2*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                            b)*gamma(a + b + 1)-8*gamma(a + b + 2)*gamma(a + 1)*gamma(a + b)*p_0*p_2*wR + 8*p_1*p_2*wR*gamma(a + 
                                                                                                                                                                                                                                                                                                               1)*gamma(a + b)*gamma(a + b + 2))/beta(a,b)/gamma(a + b)/gamma(a + b + 1)/gamma(a + b + 2)
}

int_Hp_xT1_xR2 <- function(wR, p_0, p_1, p_2, a, b) {
  1/2*gamma(b)*(2*gamma(a + b)*gamma(a + 
                                       1)*gamma(a + b + 2)*p_0*wR^2 + 2*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 
                  2*p_2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-gamma(a + b)*gamma(a + b + 1)*gamma(a + 
                                                                                                              2)*p_0*wR^2-p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-p_2*wR^2*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                            b)*gamma(a + b + 1)-2*gamma(a)*gamma(a + b + 2)*gamma(a + b + 1)*p_1*wR^2-2*p_1*wR*gamma(a + 
                                                                                                                                                                                                                                                                                                       1)*gamma(a + b)*gamma(a + b + 2)-4*p_2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 
                  p_1*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 
                                                                                                                 1) + 2*gamma(a)*gamma(a + b + 2)*gamma(a + b + 1)*p_1*wR + 2*p_2*gamma(a + 1)*gamma(a + b)*gamma(a + 
                                                                                                                                                                                                                    b + 2)-p_2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1))/beta(a,b)/gamma(a + b)/gamma(a + b + 
                                                                                                                                                                                                                                                                                                          1)/gamma(a + b + 2)
}

int_Ha_xT1_xR2 <- function(wR, p_0, p_1, p_2, a, b) {
  1/2*gamma(b)*(-4*p_2^2*wR*gamma(a + 
                                    1)*gamma(a + b)*gamma(a + b + 2) + 2*gamma(a + b + 2)*gamma(a + b + 1)*gamma(a)*p_1*p_2*wR^2 + 
                  2*gamma(a + b + 1)*gamma(a + b + 2)*gamma(a)*p_1*p_2 + 2*p_0*p_1*wR^2*gamma(a + 2)*gamma(a + 
                                                                                                             b)*gamma(a + b + 1)-2*p_0*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                  2*p_1*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*gamma(a + b + 2)*gamma(a)*gamma(a + b 
                                                                                                                + 1)*p_0*p_1*wR^2-4*p_0*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 4*gamma(a + b + 
                                                                                                                                                                                                        2)*gamma(a + b)*gamma(a + 1)*p_0*p_2*wR^2-4*p_1*p_2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                   2)-p_0*p_1*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_0*p_2*wR*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                b)*gamma(a + b + 1)-3*p_1*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_0*p_1*wR*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1)*gamma(a + b)*gamma(a + b + 2)-4*gamma(a)*gamma(a + b + 1)*gamma(a + b + 2)*p_1*p_2*wR + 
                  2*p_2^2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-2*gamma(a + b + 2)*gamma(a + b + 
                                                                                                     1)*gamma(a)*p_1^2*wR^2 + 2*gamma(a + b + 2)*gamma(a + b + 1)*gamma(a)*p_1^2*wR + 2*gamma(a + 
                                                                                                                                                                                                b)*gamma(a + b + 2)*gamma(a + 1)*p_0*p_2-2*p_1*p_2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                                                                                     2)-gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)*p_0^2*wR^2-p_1^2*wR^2*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                              b)*gamma(a + b + 1)-p_2^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2)*gamma(a + b)*gamma(a + 1)*p_0^2*wR^2 + 2*p_1^2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 
                  p_1^2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-2*p_1^2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b 
                                                                                                                 + 2)-p_0*p_2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_2^2*wR*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                           b)*gamma(a + b + 1) + p_1*p_2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_2^2*gamma(a + 
                                                                                                                                                                                                                                                                                                      1)*gamma(a + b)*gamma(a + b + 2)-p_2^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-4*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                  2)*gamma(a + 1)*gamma(a + b)*p_0*p_2*wR + 6*p_1*p_2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           2))/beta(a,b)/gamma(a + b)/gamma(a + b + 1)/gamma(a + b + 2)
}

int_Hp_xT2_xR0 <- function(wR, p_0, p_1, p_2, a, b) {
  1/4*gamma(b)*(4*gamma(a)*gamma(a + b + 
                                   1)*gamma(a + b + 2)*p_2*wR^2-2*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 
                                                                                                             2)-4*p_2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + gamma(a + b)*gamma(a + b + 1)*gamma(a + 
                                                                                                                                                                                                              2)*p_0*wR^2 + p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + p_2*wR^2*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                                                                                                                                b)*gamma(a + b + 1) + 2*p_1*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-2*gamma(a + b)*gamma(a + b 
                                                                                                                                                                                                                                                                                                                                                                                                               + 1)*gamma(a + 2)*p_0*wR-p_1*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + gamma(a + b)*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 b + 1)*gamma(a + 2)*p_0)/beta(a,b)/gamma(a + b)/gamma(a + b + 1)/gamma(a + b + 2)
}

int_Ha_xT2_xR0 <- function(wR, p_0, p_1, p_2, a, b) {
  1/4*gamma(b)*(4*gamma(a)*gamma(a + b + 
                                   1)*gamma(a + b + 2)*p_2^2*wR^2-4*gamma(a + b + 2)*gamma(a + b + 
                                                                                             1)*gamma(a)*p_1*p_2*wR^2-2*p_0*p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                  2*p_0*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-2*p_1*p_2*wR^2*gamma(a + 2)*gamma(a + 
                                                                                                                b)*gamma(a + b + 1) + 4*gamma(a + b + 2)*gamma(a)*gamma(a + b + 1)*p_0*p_2*wR^2 + 
                  2*p_0*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-4*gamma(a + b + 2)*gamma(a + b)*gamma(a + 
                                                                                                                    1)*p_0*p_2*wR^2 + 6*p_1*p_2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 3*p_0*p_1*wR*gamma(a + 
                                                                                                                                                                                                                       2)*gamma(a + b)*gamma(a + b + 1)-2*p_0*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                  p_1*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-4*p_0*p_1*wR*gamma(a + 1)*gamma(a + b)*gamma(a 
                                                                                                                     + b + 2) + 4*gamma(a)*gamma(a + b + 1)*gamma(a + b + 2)*p_1*p_2*wR-4*p_2^2*wR^2*gamma(a + 1)*gamma(a 
                                                                                                                                                                                                                        + b)*gamma(a + b + 2) + 4*gamma(a)*gamma(a + b + 2)*gamma(a + b + 1)*p_0*p_2-4*gamma(a + b)*gamma(a 
                                                                                                                                                                                                                                                                                                                          + b + 2)*gamma(a + 1)*p_0*p_2 + gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)*p_0^2*wR^2 + 
                  p_1^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + p_2^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a 
                                                                                                                     + b + 1)-2*p_1^2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-2*gamma(a + 2)*gamma(a + b)*gamma(a 
                                                                                                                                                                                                                        + b + 1)*p_0^2*wR-p_1^2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_1^2*wR*gamma(a + 
                                                                                                                                                                                                                                                                                                                   1)*gamma(a + b)*gamma(a + b + 2)-p_0*p_1*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                  p_0*p_2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_0*p_1*gamma(a + 1)*gamma(a + b)*gamma(a + b 
                                                                                                                 + 2) + gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)*p_0^2 + 8*gamma(a + b + 2)*gamma(a + 1)*gamma(a + 
                                                                                                                                                                                                                   b)*p_0*p_2*wR-4*p_1*p_2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-8*gamma(a + b + 2)*gamma(a + b 
                                                                                                                                                                                                                                                                                                                  + 1)*gamma(a)*p_0*p_2*wR)/beta(a,b)/gamma(a + b)/gamma(a + b + 1)/gamma(a + b + 2)
}

int_Hp_xT2_xR1 <- function(wR, p_0, p_1, p_2, a, b) {
  -1/4*gamma(b)*(8*gamma(a)*gamma(a + b + 
                                    1)*gamma(a + b + 2)*p_2*wR^2-4*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 
                                                                                                              2)-8*p_2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 2*gamma(a + b)*gamma(a + b + 1)*gamma(a + 
                                                                                                                                                                                                                 2)*p_0*wR^2 + 2*p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_2*wR^2*gamma(a + 
                                                                                                                                                                                                                                                                                                          2)*gamma(a + b)*gamma(a + b + 1)-8*gamma(a)*gamma(a + b + 1)*gamma(a + b + 2)*p_2*wR + 
                   4*p_1*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 8*p_2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b 
                                                                                                                  + 2)-2*gamma(a + b)*gamma(a + b + 1)*gamma(a + 2)*p_0*wR-2*p_1*wR*gamma(a + 2)*gamma(a + b)*gamma(a 
                                                                                                                                                                                                                    + b + 1)-2*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-2*p_1*gamma(a + 1)*gamma(a + b)*gamma(a 
                                                                                                                                                                                                                                                                                                                       + b + 2) + p_1*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1))/beta(a,b)/gamma(a + b)/gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                 1)/gamma(a + b + 2)
}

int_Ha_xT2_xR1 <- function(wR, p_0, p_1, p_2, a, b) {
  -1/4*gamma(b)*(8*p_2^2*wR*gamma(a + 
                                    1)*gamma(a + b)*gamma(a + b + 2) + 8*gamma(a)*gamma(a + b + 1)*gamma(a + b + 2)*p_2^2*wR^2 + 
                   p_1^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-2*p_1^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 
                                                                                                              2)-8*gamma(a + b + 2)*gamma(a + b + 1)*gamma(a)*p_1*p_2*wR^2-4*gamma(a + b + 1)*gamma(a + b + 
                                                                                                                                                                                                      2)*gamma(a)*p_1*p_2-4*p_0*p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                   4*p_0*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-4*p_1*p_2*wR^2*gamma(a + 2)*gamma(a + 
                                                                                                                 b)*gamma(a + b + 1) + 8*gamma(a + b + 2)*gamma(a)*gamma(a + b + 1)*p_0*p_2*wR^2 + 
                   4*p_0*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-8*gamma(a + b + 2)*gamma(a + b)*gamma(a + 
                                                                                                                     1)*p_0*p_2*wR^2 + 12*p_1*p_2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 4*p_0*p_1*wR*gamma(a 
                                                                                                                                                                                                                       + 2)*gamma(a + b)*gamma(a + b + 1)-4*p_0*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                   4*p_1*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-4*p_0*p_1*wR*gamma(a + 1)*gamma(a + 
                                                                                                             b)*gamma(a + b + 2) + 8*gamma(a)*gamma(a + b + 1)*gamma(a + b + 2)*p_1*p_2*wR-8*p_2^2*wR^2*gamma(a + 
                                                                                                                                                                                                                1)*gamma(a + b)*gamma(a + b + 2) + 4*p_1*p_2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 2*gamma(a 
                                                                                                                                                                                                                                                                                                                  + 2)*gamma(a + b)*gamma(a + b + 1)*p_0^2*wR^2 + 2*p_1^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                 1) + 2*p_2^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-4*p_1^2*wR^2*gamma(a + 1)*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b)*gamma(a + b + 2)-2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)*p_0^2*wR-2*p_1^2*wR*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             2)*gamma(a + b)*gamma(a + b + 1) + 4*p_1^2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             2)-p_0*p_1*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-8*gamma(a)*gamma(a + b + 1)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       2)*p_2^2*wR-2*p_2^2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-p_1*p_2*gamma(a + 2)*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      b)*gamma(a + b + 1) + 8*gamma(a + b + 2)*gamma(a + 1)*gamma(a + b)*p_0*p_2*wR-12*p_1*p_2*wR*gamma(a 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        + 1)*gamma(a + b)*gamma(a + b + 2)-8*gamma(a + b + 2)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1)*gamma(a)*p_0*p_2*wR)/beta(a,b)/gamma(a + b)/gamma(a + b + 1)/gamma(a + b + 2)
}

int_Hp_xT2_xR2 <- function(wR, p_0, p_1, p_2, a, b) {
  1/4*gamma(b)*(4*gamma(a)*gamma(a + b + 
                                   1)*gamma(a + b + 2)*p_2*wR^2 + gamma(a + b)*gamma(a + b + 1)*gamma(a + 2)*p_0*wR^2 + 
                  p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b 
                                                                                                                 + 1)-2*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-4*p_2*wR^2*gamma(a + 1)*gamma(a + 
                                                                                                                                                                                                            b)*gamma(a + b + 2)-8*gamma(a)*gamma(a + b + 1)*gamma(a + b + 2)*p_2*wR-p_1*wR*gamma(a + 2)*gamma(a 
                                                                                                                                                                                                                                                                                                              + b)*gamma(a + b + 1)-2*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_1*wR*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                           1)*gamma(a + b)*gamma(a + b + 2) + 8*p_2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 
                  4*gamma(a)*gamma(a + b + 2)*gamma(a + b + 1)*p_2 + p_2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 
                                                                                                           1)-4*p_2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2))/beta(a,b)/gamma(a + b)/gamma(a + b + 1)/gamma(a 
                                                                                                                                                                                                              + b + 2)
}

int_Ha_xT2_xR2 <- function(wR, p_0, p_1, p_2, a, b) {
  1/4*gamma(b)*(8*p_2^2*wR*gamma(a + 1)*gamma(a 
                                              + b)*gamma(a + b + 2) + 4*gamma(a)*gamma(a + b + 1)*gamma(a + b + 2)*p_2^2*wR^2-4*gamma(a + b + 
                                                                                                                                        2)*gamma(a + b + 1)*gamma(a)*p_1*p_2*wR^2-2*p_0*p_1*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) 
                + 2*p_0*p_2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-2*p_1*p_2*wR^2*gamma(a + 2)*gamma(a + 
                                                                                                                b)*gamma(a + b + 1) + 4*gamma(a + b + 2)*gamma(a)*gamma(a + b + 1)*p_0*p_2*wR^2 + 
                  2*p_0*p_1*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2)-4*gamma(a + b + 2)*gamma(a + b)*gamma(a + 
                                                                                                                    1)*p_0*p_2*wR^2 + 6*p_1*p_2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + p_0*p_1*wR*gamma(a + 
                                                                                                                                                                                                                     2)*gamma(a + b)*gamma(a + b + 1)-2*p_0*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                  3*p_1*p_2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 4*gamma(a)*gamma(a + b + 1)*gamma(a + b + 
                                                                                                                2)*p_1*p_2*wR-4*p_2^2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + 4*gamma(a + b + 2)*gamma(a + 
                                                                                                                                                                                                                   b + 1)*gamma(a)*p_2^2 + 2*p_1*p_2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + gamma(a + 2)*gamma(a 
                                                                                                                                                                                                                                                                                                                     + b)*gamma(a + b + 1)*p_0^2*wR^2 + p_1^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 
                  p_2^2*wR^2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-2*p_1^2*wR^2*gamma(a + 1)*gamma(a + b)*gamma(a 
                                                                                                                     + b + 2)-p_1^2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1) + 2*p_1^2*wR*gamma(a + 1)*gamma(a + 
                                                                                                                                                                                                                    b)*gamma(a + b + 2) + p_0*p_2*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-8*gamma(a)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                1)*gamma(a + b + 2)*p_2^2*wR-2*p_2^2*wR*gamma(a + 2)*gamma(a + b)*gamma(a + b + 1)-p_1*p_2*gamma(a + 
                                                                                                                                                                                                                                                                                                                                                                                                                   2)*gamma(a + b)*gamma(a + b + 1)-4*p_2^2*gamma(a + 1)*gamma(a + b)*gamma(a + b + 2) + p_2^2*gamma(a 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     + 2)*gamma(a + b)*gamma(a + b + 1)-8*p_1*p_2*wR*gamma(a + 1)*gamma(a + b)*gamma(a + b + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       2))/beta(a,b)/gamma(a + b)/gamma(a + b + 1)/gamma(a + b + 2)
}
